### ISSUE TITLE
fix: Resolve error when substitution text contains whitespace

### ISSUE THREAD

**Issue by junghoon-vans** [junghoon-vans/varst-action#17]
Error Log
---

![error log](https://user-images.githubusercontent.com/44942700/209692052-2a74e08e-bdf4-4452-944f-3fcfc12ec8ec.png)

Temporary Solution
---

### AS-IS

```yml
 - name: Run varst action
   uses: junghoon-vans/varst-action@v1
   with:
      substitutions: 'whitespace with inline style=make some error'
```

This error occurs when substitution contains whitespace with `inline style`.
For example, the above workflow make an error.

### TO-BE

```yml
 - name: Run varst action
   uses: junghoon-vans/varst-action@v1
   with:
      substitutions: >-
        'whitespace with folded block style=not make any error'
```

Use `folded block scalar` style until this issue is closed.
